---
- hosts: hosts_vitamui_ingest_internal
  gather_facts: no
  any_errors_fatal: true
  roles:
    - vitamui
  vars:
    vitamui_struct: "{{ vitamui.security_internal }}"
    password_keystore: "{{ keystores.server.security_internal }}"
    password_manager_keystore: "{{ keystores.server.security_internal }}"
    password_truststore_server: "{{ truststores.server }}"
    vitamui_certificate_client_type: "iam"
    password_truststore: "{{ truststores.client_iam }}"
    other_stores: []
    consul_tags: "ingest-internal, api, internal"

- hosts: hosts_vitamui_iam_external
  gather_facts: no
  any_errors_fatal: true
  roles:
    - vitamui
  vars:
    vitamui_struct: "{{ vitamui.iam_external }}"
    vitamui_certificate_client_type: "iam"
    password_keystore: "{{ keystores.server.iam_external }}"
    password_manager_keystore: "{{ keystores.server.iam_external }}"
    password_truststore_server: "{{ truststores.server }}"
    password_truststore: "{{ truststores.client_iam }}"
    other_stores: ["security_internal","iam_internal"]
    consul_tags: "iam-external, api, external"


- hosts: hosts_ui_identity
  gather_facts: no
  any_errors_fatal: true
  roles:
    - vitamui
  vars:
    vitamui_struct: "{{ vitamui.identity }}"
    password_keystore: "{{ keystores.server.ui_identity }}"
    password_manager_keystore: "{{ keystores.server.ui_identity }}"
    password_truststore_server: "{{ truststores.server }}"
    vitamui_certificate_client_type: "iam"
    password_truststore: "{{ truststores.client_iam }}"
    other_stores: ["iam_external"]
    consul_tags: "ui-identity, ui"
