spring:
  profiles:
    active: dev,swagger

  cloud:
    consul:  #disable for dev
      enabled: false
      discovery:
        enabled: false
        register: false

server:
  host: dev-ingest.vitamui.com
  port: 9008
  scheme: https
  ssl:
    key-store: src/main/config/ui-ingest.jks
    key-store-password: jkspasswd
    key-password: jkspasswd
management:
  server:
    address: localhost
    port: 9108
    ssl:
      enabled: false

ui-ingest:
  iam-external-client:
    server-host: localhost
    server-port: 8083
    secure: true
    ssl-configuration:
      keystore:
        key-path: src/main/config/ui-ingest.jks
        key-password: jkspasswd
        type: JKS
      truststore:
        key-path: src/main/config/truststore.jks
        key-password: jkspasswd
      hostname-verification: false
  ingest-external-client:
    server-host: localhost
    server-port: 8088
    secure: true
    ssl-configuration:
      keystore:
        key-path: src/main/config/ui-ingest.jks
        key-password: jkspasswd
        type: JKS
      truststore:
        key-path: src/main/config/truststore.jks
        key-password: jkspasswd
      hostname-verification: false
  base-url:
    portal: "https://dev-portal.vitamui.com:4200"
  portal-categories:
    ingests:
      title: "Suivi des Versements"
      displayTitle: true
      order: 4
    administrators:
      title: "Management"
      displayTitle: true
      order: 2
    settings:
      title: "Paramétrage"
      displayTitle: true
      order: 3
    users:
      title: ""
      displayTitle: false
      order: 1

ui:
  url: "https://dev-ingest.vitamui.com:4202"
  redirect-url: https://dev-ingest.vitamui.com:9008/${ui-prefix}

cas:
  internal-url: https://dev.vitamui.com:8080/cas
  external-url: https://dev.vitamui.com:8080/cas
  callback-url: ${ui.url}/ingest-api/callback
  ssl:
    trust-store: src/main/config/truststore.jks
    trust-store-password: jkspasswd

logging:
  level:
    fr.gouv.vitamui: DEBUG
    org.springframework.web: INFO
    reactor.netty.*: DEBUG

management.endpoints.web.exposure.include: "*"
# Uncomment if you want to use you specific logback config.
#logging:
#  config: src/main/config/logback.xml
